### ISSUE TITLE
Cite your source + README

### ISSUE THREAD

**Issue by the872** [psheu/TwitterEngine#1]
You used a lot of code from [here](https://github.com/twitter/twitter-text) but I did not see you reference it in any of the documents.

What I suggest is that you create a README file and place the resources that you used in there, respectively.

**Comment by jthompson18** [comment]
@psheu this seems like an exact copy of https://github.com/twitter/twitter-text/tree/master/java/src/com/twitter with comments changed. I can understand reusing and existing implementation but it has been done without citations and without the proper license -> https://github.com/twitter/twitter-text/blob/master/LICENSE. As such you are in violation of the License that Twitter uses and open to litigation. You may want to update this to include the license information at the very least

**Comment by psheu** [comment]
I didn't realize that. Thanks!

**Comment by jthompson18** [comment]
@psheu I wouldn't recommend closing this issue until you have added the license. You can close and issue via commit by adding "fixes user/repo/#issueNumber" to the commit message

**Comment by psheu** [comment]
@jthompson18 I just redid my project, would you mind peer reviewing the new code? Thanks!

**Comment by jthompson18** [comment]
@psheu I can review your code tomorrow evening. I'll open a new ticket with my feedback. Feel free to close this now.
